# The api key, secret key, and canvas page name are required to get started
# Tunnel configuration is only needed if you are going to use the facebooker:tunnel Rake tasks
# Your callback url in Facebook should be set to http://public_host:public_port
# If you're building a Facebook connect site, 
#    change the value of set_asset_host_to_callback_url to false
# To develop for the new profile design, add the following key..
# api: new
# remove the key or set it to anything else to use the old facebook design.
# This should only be necessary until the final version of the new profile is released.

development:
  api_key: e1a0776281b0ab486e48fef96157a8cc
  secret_key: 9cce5d1277b10fc199319cafb7ae14b6
  canvas_page_name: JWLapp
  callback_url: http://127.0.0.1:3001/
  pretty_errors: true
  set_asset_host_to_callback_url: false
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000
    server_alive_interval: 0

test:
  api_key: 
  secret_key: 
  canvas_page_name: 
  callback_url:
  set_asset_host_to_callback_url: true
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000
    server_alive_interval: 0

production:
  api_key: 9bd53c8de2bcf67a1db236c662d55e16
  secret_key: 28658e846895b594da8f128431d21106
  canvas_page_name: StatusMee
  callback_url: http://appconnect.heroku.com/
  pretty_errors: true
  set_asset_host_to_callback_url: false
  tunnel:
    public_host_username: jwluo21
    public_host: http://heroku.com/
    public_port: 4007
    local_port: 3000
    server_alive_interval: 0
